### PR TITLE
Add Sonarr file renaming

### PR DESCRIPTION
**Pull request by Mundokiir**
## Description of the pull request
This PR seeks to achieve the following goals:

1. Add the option to have Sonarr run its built in rename function. Useful when re-encoding files in situations where Sonarr does file renaming and has encoding information included in the naming format.
2. This is all in line with the similar changes made to the Notify Sonarr plugin, including logging changes and error handling.
3. The built in "RenameSeries" API command appears broken (at least on my Sonarr 3.0.9.1549 install) so instead I'm simulating how the Sonarr UI implements this by first querying episodes in which the title doesn't match the video format and requesting renaming of the returned results. This seems to work well.
4. I attempted to back-port the description changes made by @Josh5 to the Notify Radarr plugin into this description as well, but please feel free to let me know if I should further modify.

## CLA

- [X] I agree that by opening a pull requests I am handing over copyright ownership of my work contained in that pull request to the owner of this git project. My contribution will become licensed under the same license as the overall project. This extends upon paragraph 11 of the Terms & Conditions stipulated in the GPL v3.0

## Checklist 

- [X] I have ensured that my pull request is being opened to merge into the correct branch.
  - Merging into "master" as that's the only branch.
- [ ] (If submitting a new plugin) I have included a copy of the GPL v3.0 [LICENSE](../LICENSE) file in my plugin directory.
  - Not a new plugin.
- [X] I have ensured that all new python file contributions contain the correct header as stipulated in the [Contributing Docs](CONTRIBUTING.md#opening-pull-requests).
  - Header already exists :)

## Testing
I've successfully created my own plugin repo and tested the functionality in a live unmanic instance [v0.2.3~b517463]. The test repo is here: https://github.com/Mundokiir/unmanic-plugins

### CODE REVIEW

**Comment by Josh5** [comment]
What is your opinion about https://github.com/Unmanic/plugin.notify_sonarr/pull/1 ?

**Comment by Mundokiir** [comment]
I'm a fan of the idea there. Any reduction of dependency is good in my book and I'm not a huge fan of the limitations built into pyarr. I'm happy to re-work my changes here into the new session method if you decide to move forward with that instead.

**Comment by Josh5** [comment]
Yea, I think it is worth doing. I was holding off on merging that other pr as I don't have the time at the moment to fully test it. If you are happy to take ownership of it,  that would be awesome!

My next project with this plug-in was to add the ability to receive web hooks from sonarr. I can carry on with that one if you want to fix up my changes after I merge this PR.

**Comment by Mundokiir** [comment]
My free time tends to come in bursts (which is why it took me a while to submit this PR) so I might not be able to get to it for a few weeks but am happy to do so when I can.

**Pull request merged**
